### ISSUE TITLE
no such file or directory: '/tmp/pip-build-jykvuD/YellowFin/README.md

### ISSUE THREAD

**Issue by CanoeFZH** [JianGoForIt/YellowFin#21]
```
tensorflow) ➜  models git:(master) ✗ pip install  YellowFin
Collecting YellowFin
  Using cached Yellowfin-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jykvuD/YellowFin/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/canoe/Project/tensorflow/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-jykvuD/YellowFin/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jykvuD/YellowFin/
```

**Comment by jilljenn** [comment]
May it be related to Python 3 instead of Python 2.7?

**Comment by BaeSeulki** [comment]
Collecting Yellowfin
  Using cached Yellowfin-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-akf32_4s/Yellowfin/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-build-akf32_4s/Yellowfin/README.md'

**Comment by treper** [comment]
I got the same error, any solutions?

**Comment by franva** [comment]
same here, any update?

**Comment by tipsy7** [comment]
解决办法：yellowfin不安装也能用。先把压缩包下载下来，拷贝YellowFin-master\tuner_utils文件夹中的三个文件放到  你的代码中有from yellowfin import YFOptimizer那个程序目录下，就能用yellowfin了
Solution: Yellowfin can be used without installation. First download the compressed package, copy the three files in the YellowFin-master\tuner_utils folder into your code from the yellowfin import YFOptimizer that program folder, you can use yellowfin
